### ISSUE TITLE
implement adapter methods

### ISSUE THREAD

**Issue by twilson63** [hyper63/hyper-adapter-sqs#2]
- [x] index 
- [x] create
  - [x] if no bucket create s3 bucket
  - [x] if no queue file create queue file
  - [x] if no sqs queue create sqs queue 
- [x] delete
  - [x] if last queue - delete queue file
  - [x] if last queue - delete sqs queue
  - [x] if last queue - delete s3 bucket 
- [x] post
- [x] get
- [x] retry
- [x] cancel

**Comment by twilson63** [comment]
Rethinking implementation of get, retry and cancel, why are they there? Surely they are needed, but sqs does not support these types of calls. But we also have access to a persistent layer s3. 

### get

To support the `get` message, what if we called `putObject` of the queue message to our s3 bucket `${queue}/${MessageId}` and adding the status property of READY to the msg, then we could support the get function, by simply allowing the user to get a list of jobs that are either in the READY or ERROR status, using the `listObjects` from the s3 bucket. When we delete the message, we also delete the object. - If the asyncFetch does not return a 2xx message, then we need to change the object status to 'ERROR', even though we delete the message from the queue. -> Yay! We have a get message feature! Supporting status=READY and status=ERROR. 

### retry 

To support the `retry` we must have the get function working, then. if the user submits a retry, it must be for a message id that has errored out. So the retry process, will get the object from s3 by the message id, then create a new message and send it to the sqs queue, then remove the old object from s3. This should complete the retry workflow.

### cancel

In order to cancel a job, we need to be able to find the job in the s3 bucket, and it should be marked with a status of READY, we change the status for the job to CANCELLED. Then we modify the retrieveMessage flow, to get the object from s3 and check if it 
contains a status of `CANCELLED`, and if it does, we do not send the message to the target, we delete it and delete object from the bucket

**Comment by TillaTheHun0** [comment]
## get

>  If the asyncFetch does not return a 2xx message

This is the fetch to get the _actual_ message on the queue? If so, then this makes sense to me. We would have to take care of making sure this object and s3 is kept in sync with the message on sqs.

## retry

How does this intersect with [visibility timeout](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html) on sqs? If a handler fails to process the message, then the message will remain on the queue, and after the visibility timeout elapses, can be picked up again, functioning as a "retry"

## cancel

There seems to be another state a message can be in here, which is something like "Processing", and I don't think that is cancelable and we should communicate that to the consumer attempting to cancel a job, perhaps with an error.

Otherwise, a consumer may think they canceled a job, but in reality, the message was already being processed by a worker.

**Comment by twilson63** [comment]
> This is the fetch to get the actual message on the queue? If so, then this makes sense to me. We would have to take care of making sure this object and s3 is kept in sync with the message on sqs. This is the fetch that posts the queue message to the target endpoint.

> How does this intersect with visibility timeout on sqs? If a handler fails to process the message, then the message will remain on the queue, and after the visibility timeout elapses, can be picked up again, functioning as a "retry"

Good question, since these messages are processing every 10 seconds I don't know how much that is in play. I think the purpose of the retry is to resubmit jobs that failed because the webhook target was down, which I don't think this would effect anything sqs is doing.

> There seems to be another state a message can be in here, which is something like "Processing", and I don't think that is 
> cancelable and we should communicate that to the consumer attempting to cancel a job, perhaps with an error.

> Otherwise, a consumer may think they canceled a job, but in reality, the message was already being processed by a worker.

This may be the case, let me trace through the steps and as get further down the implementation path, lets re check this one. So far I think there can only be three states, READY, ERROR, and CANCELLED, but once the logic is implemented we can expand if there is a chance of a 4th state as a result of SQS not doing its job.

**Comment by TillaTheHun0** [comment]
> but once the logic is implemented we can expand if there is a chance of a 4th state as a result of SQS not doing its job.

I don't see this as sqs not doing its job, but just keeping the status of the mesage doc in s3 in sync with the status of the message on sqs. When a message is read from the queue, sqs will automatically dequeue the messsage up to the visibility timeout. This is effectively "processing" state and prevents other workers from picking it up and also so the message cannot be canceled while its being processed (which is semantically invalid). We would need to reflect that in the message doc for similar reasons, if I am understanding this solution.

**Comment by twilson63** [comment]
> I don't see this as sqs not doing its job, but just keeping the status of the mesage doc in s3 in sync with the status of the message on sqs. When a message is read from the queue, sqs will automatically dequeue the messsage up to the visibility timeout. This is effectively "processing" state and prevents other workers from picking it up and also so the message cannot be canceled while its being processed (which is semantically invalid). We would need to reflect that in the message doc for similar reasons, if I am understanding this solution.

Right but I am deleting the message once it is retrieved and processed, is this still in play??

**Comment by TillaTheHun0** [comment]
Do you mean you're deleting the doc from s3 once the payload is dispatched to the target? Or once the target responds with a success?

If it's the latter, then isn't there a period of time where the doc in s3 would still exist, but not be cancelable because it's undergoing processing?

**Comment by twilson63** [comment]
No, I am deleting the sqs message from the queue after it is read.

**Comment by twilson63** [comment]
I think it will be clear once implemented, if the the fetch post succeeds the msg from the queue is deleted, if the fetch post fails, the msg from the queue is still deleted but the object in s3 is set to a status of error

**Comment by TillaTheHun0** [comment]
closed by #6
